spring:

  mvc:
    format:
      date: yyyy-MM-dd

  datasource:
    url: jdbc:h2:mem:tmsDb
    username: sa
    password: password
    driverClassName: org.h2.Driver

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect

  jackson:
    default-property-inclusion: non_null